#!/bin/bash

set -e

if [ -n "$(git status --porcelain)" ];
then
    git status
    echo "Uncommitted changes. Exiting."
    exit 1
fi

git clean -fdx
npm install
npm run test
# List files that will be included by running npm pack
# and then listing all files that it includes in the tar.
npm pack
tar tvzf *.tgz
rm *.tgz

echo "Do you want to publish this?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) npm publish --access public; break;;
        No ) exit;;
    esac
done