name: Publish to npm
on:
    push:
        tags:
            - v*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v1
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: npm ci
            - run: npm run lint
            - run: npm run build
            - run: npm test
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
